// <auto-generated />
using System;
using Amazon_Services_Test_App_FSDM_Oct_24_4_az.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon_Services_Test_App_FSDM_Oct_24_4_az.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon_Services_Test_App_FSDM_Oct_24_4_az.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronic",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest Apple smartphone with A17 Pro chip",
                            Name = "iPhone 15 Pro",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic gaming chair with lumbar support",
                            Name = "Gaming Chair",
                            Price = 349.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Books",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive guide for learning C# and .NET",
                            Name = "C# Programming Book",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sports",
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable sport shoes for daily running",
                            Name = "Running Shoes",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Home Appliance",
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automatic coffee machine for home use",
                            Name = "Coffee Maker",
                            Price = 159.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
